### ISSUE TITLE
请问如何访问

### ISSUE THREAD

**Issue by lightnine** [liyifeng1994/seckill#2]
你好：
这个工程现在我已经导入eclipse中，在tomcat中已经启动了本工程，但是访问http://localhost:8080/seckill/list.jsp报404的错误，当时我看了访问网址就是这个，不知道问题出在哪里，能说下嘛？

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by liyifeng1994** [comment]
前端的代码我没敲上去哈，只关注后端代码
